import burger from "../public/assets/Iteration-2-assets/pictures/food-3.png";
import pizza from "../public/assets/Iteration-2-assets/pictures/form-banner.png";
const pizzas = [
  {
    id: "1",
    isim: "Position Absolute Acı Pizza",
    image: `${pizza}`,
    varsayilanMalzemeler: ["Pepperoni", "Sosis", "Mısır", "Sucuk", "Biber"],
    pizzaAciklamasi:
      "Frontent Dev olarak hala position:absolute kullanıyorsan bu çok acı pizza tam sana göre. Pizza, domates, peynir ve genellikle çeşitli diğer malzemelerle kaplanmış, daha sonra geleneksel olarak odun ateşinde bir fırında yüksek sıcaklıkta pişirilen, genellikle yuvarlak, düzleştirilmiş mayalı buğday bazlı hamurdan oluşan İtalyan kökenli lezzetli bir yemektir. . Küçük bir pizzaya bazen pizzetta denir.",
    fiyat: 85.5,
    boyutSecenekleri: ["S", "M", "L"],
    hamurSecenekleri: ["İnce", "Normal", "Kalın"],
    ekstraMalzemeFiyat: 5,
    tumMalzemeler: [
      "Pepperoni",
      "Sosis",
      "Kanada Jambonu",
      "Tavuk Izgara",
      "Soğan",
      "Domates",
      "Sucuk",
      "Jalapeno",
      "Biber",
      "Sarımsak",
      "Kabak",
      "Ananas",
      "Mısır",
      "Parmesan Peyniri",
    ],
    puan: 4.9,
    puanVerenSayisi: 200,
  },
  {
    id: "2",
    isim: "Başka Bir Pizza",
    image: `${pizza}`,
    varsayilanMalzemeler: ["Sucuk", "Soğan"],
    pizzaAciklamasi: "Başka bir pizza açıklaması.",
    fiyat: 90,
    boyutSecenekleri: ["Küçük", "Orta"],
    hamurSecenekleri: ["İnce"],
    ekstraMalzemeFiyat: 6,
    tumMalzemeler: ["Sucuk", "Soğan", "Tavuk Izgara"],
    puan: 4.2,
    puanVerenSayisi: 150,
  },
  {
    id: "3",
    isim: "Hackathkon Burger Menü",
    image: `${burger}`,
    varsayilanMalzemeler: ["Sucuk", "Soğan"],
    pizzaAciklamasi:
      "Burger King® eşsiz lezzeti Triple Whopper® Menü şimdi Teknolojik Yemekler'de sende hemen sipariş ver yemeğin anında kapında olsun.Triple Whopper® + Patates Kızartması (Orta) + Kutu İçecek ",
    fiyat: 90,
    boyutSecenekleri: ["S", "M", "L"],
    hamurSecenekleri: ["İnce"],
    ekstraMalzemeFiyat: 6,
    tumMalzemeler: [
      "Sucuk",
      "Soğan",
      "Ekstra Köfte",
      "Domates",
      "Göbek Salata",
      "Turşu",
      "Ketçap",
      "Mayonez",
      "Acı Sos",
      "Hardal",
      "Patates Kızartması",
    ],
    puan: 4.2,
    puanVerenSayisi: 150,
  },
];

export default pizzas;
